version: '2.2'
services:
        elasticsearch:
                image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
                container_name: elasticsearch
                ports:
                        - 9200:9200
        logstash:
                image: docker.elastic.co/logstash/logstash:6.4.0
                container_name: logstash
                ports:
                        - 9600:9600
                depends_on:
                        - elasticsearch
        kibana:
                image: docker.elastic.co/kibana/kibana:6.4.0
                container_name: kibana
                environment:
                        ELASTICSEARCH_URL: http://elasticsearch:9200
                ports:
                        - 5601:5601
                depends_on:
                        - elasticsearch
                        - logstash
